"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const path = require("path");
const os = require("os");
exports.BRAND_NAME = "sidechat";
exports.BRAND_TITLE = "SideChat";
exports.VIEW_CONTAINER_ID = "sidechat";
exports.VIEW_ID = "sideChat.sidebar";
exports.MCP_SERVER_PREFIX = "sidechat";
exports.MANAGED_RULE_FILE_NAME = "sidechat.mdc";
exports.MAX_SESSIONS = 3;
exports.DEFAULT_SESSION_ORDER = ["1"];
exports.GLOBAL_STATE_SESSION_KEY = "sidechat.sessionMessages.v1";
exports.GLOBAL_STATE_SESSION_ORDER_KEY = "sidechat.sessionOrder.v1";
exports.GLOBAL_STATE_SESSION_MEMOS_KEY = "sidechat.sessionMemos.v1";
exports.GLOBAL_STATE_DRAFTS_KEY = "sidechat.sessionDrafts.v1";
exports.GLOBAL_STATE_LAST_WORKSPACE_PATH_KEY = "sidechat.lastWorkspacePath.v1";
exports.GLOBAL_STATE_PRESETS_KEY = "sidechat.presets.v1";
exports.MAX_SESSION_MEMO_CHARS = 200;
exports.MAX_SESSION_HISTORY_ITEMS = 80;
exports.MAX_ATTACH_BASE64_CHARS = 14_000_000;
exports.MANAGED_WORKSPACES_REGISTRY_PATH = path.join(os.homedir(), ".cursor", "sidechat-managed-workspaces.json");
exports.MESSAGES_BASE_DIR = path.join(os.homedir(), ".cursor", "sidechat-messages");
exports.MANAGED_MCP_KEY = /^sidechat-\d+$/;
